### ISSUE TITLE
describe-stack <argsfile>

### ISSUE THREAD

**Issue by pauloancheta** [unbounce/iidy#12]
Currently, to describe a stack, the user has to add `iidy describe-stack <stackname>` and if it's on a different region, the have to add it as `--region us-west-1`. And if they are more unlucky, they will have to add a `profile` which makes the command longer.

It would be great if `iidy` detects the current `stack_args.yaml` in the file. It should assume that in the current directory, there's only one `stack_args.yaml` and `template.yaml`. **Convention over configuration**

With this, after they have configured `stack_args.yaml`, they can run commands without further configuration. `iidy describe-stack` should just work, but still supporting `--stackName` and other `--` configuration

**Comment by tavisrudd** [comment]
Agreed. @lewisd32 @jpb and I discussed adding similar behaviour to all the stack commands a few weeks back.

**Comment by jpb** [comment]
I think this behaviour should work for `delete-stack` as well - perhaps iidy could determine if it was provided an args file or a stack name to `describe-stack` and `delete-stack` and Do The Right Thing™.

**Comment by alextaylor000** [comment]
+1 to this - I got a bit confused yesterday when I was trying to do `iidy describe-stack stack-args.yaml ...` or `iidy delete-stack ...`. Would be great to pull the name from stack-args.

**Comment by tavisrudd** [comment]
See PR #103.

**Comment by tavisrudd** [comment]
This is done now.
