### ISSUE TITLE
iidy should use cached assume roles

### ISSUE THREAD

**Issue by jpb** [unbounce/iidy#135]
iidy should make use of (and contribute to) AWS CLI's assumed credentials cache.

Possible implementation: https://github.com/aws/aws-sdk-js/issues/993#issuecomment-260959784

**Comment by jpb** [comment]
Temporarily resolved by #137

**Comment by tavisrudd** [comment]
I've got a stash or abandoned branch of this approach from a few months back.

**Comment by tavisrudd** [comment]
@jpb #143 uses your new branch of the aws-sdk with the caching.

**Comment by tavisrudd** [comment]
Done
