### ISSUE TITLE
Caching Assumed User Credentials

### ISSUE THREAD

**Issue by rymndhng** [unbounce/iidy#14]
Does iidy cache the credentials assumed between multiple runs (the same way the AWS CLI does?)

**Comment by tavisrudd** [comment]
I does for all the api calls that are run internally when executing an `iidy` command. I'm not sure about between invocations. That would be whatever the js aws-sdk does by default and I can't find any docs on that. Why do you ask?

**Comment by tavisrudd** [comment]
As we've discussed, I've got a prototype version working that reuses the aws cli token cache. I'm either going to push that behind a feature flag env-var or create a separate `iidy` managed cache for the sts tokens.

**Comment by tavisrudd** [comment]
set the env var `iidy_use_sts_cache=1` prior to running iidy and it will use the aws cli's cache if it's present and not expired.
