### ISSUE TITLE
Show parameters in command metadata/stack details output

### ISSUE THREAD

**Issue by jpb** [unbounce/iidy#149]
When running commands like `iidy create-stack` or `iidy update-stack`, a lot of useful information is shown as output:

```
Command Metadata:
 CFN Operation:           UPDATE_STACK
 iidy Environment:        production
 Region:                  us-west-2
 CLI Arguments:           region=us-west-2, profile=null, argsfile=stack-args.yaml
...
 iidy Version:            1.6.6-rc4

Stack Details:
 Name:                    my-stack
 Status                   UPDATE_IN_PROGRESS
 Capabilities:            None
 Service Role:            ...
...
```

It would be useful if the resolved values of `Parameters` was printed as well. This can help give a better understanding of what is going on, as the value of parameters can come from sources that are not readily available (such as environment variables, files, SSM parameters, etc). Including this data will make understanding what is going on much easier.

I wonder if we would be able to hide `NoEcho` parameters from this output.

**Comment by tavisrudd** [comment]
Other than handling `NoEcho`, can you think of anything we'd need to be careful of or reasons not to do this?
