### ISSUE TITLE
Allowing use of "UsePreviousValue=true" with parameters in stack-args.yml

### ISSUE THREAD

**Issue by dannosaur** [unbounce/iidy#170]
Cloudformation has an additional flag when updating stacks "UsePreviousValue=true" which allows you to essentially only send parameters which you have values for (for instance, CI sending over only URLs to new application bundles, and informing Cloudformation to use whatever values it has for all other parameters).

This starts to get a bit tricky when I intend to integrate CI with our Cloudformation stacks, which will go forth and update only 2 of over a dozen parameters to trigger a deployment. At which point, the stack-args.yml file becomes out of date, and there then becomes a danger of re-deploying old code if the parameters in the stack-args.yml file aren't syncronized manually with the stack's current configuration prior to executing an update-stack or create-changeset (though arguably the create-changeset command would show up a re-deployment and it can be cancelled, but still requires that the parameters in the stack-args.yml file are manually syncronized prior to running any further commands on the stack).

Is it, or would it be possible to leverage the "UsePreviousValue" flag of parameters inside the stack-args.yml file, so that CI can control certain parameters without affecting the stack-args.yml file (and thus having to implement some kind of system that gets the CI to actually rewrite the stack-args.yml file and commit it back to source control)?

```
UsePreviousValueParameters:
   - MyZipFileBundle
```

Or something to that effect? My thinking in a create-stack scenario is that this list is effectively ignored. The parameters can still be populated in the standard `Parameters` dictionary, but then are ignored in subsequent update-stack commands.

Thoughts?

**Comment by tavisrudd** [comment]
👍 An alternate approach would be 
```
Parameters:
  Foo: 1234
  Bar: 
    value: blah
    use-previous: true
```

**Comment by tavisrudd** [comment]
@jpb @tuff do you have any syntax preference here?

**Comment by jpb** [comment]
I think I prefer the `UsePreviousValueParameters` option (and a matching `--use-previous-parameter-values ...`). I'm not a fan of the datatype of `Parameters` changing based on what features you're using.

Not required for this, but it is another opportunity to improve the user experience by [filtering out imports](https://github.com/unbounce/iidy/blob/master/src/preprocess/filter.ts) that are not needed. If I specify `--use-previous-parameter-values Foo`, I wouldn't want to have to provide imports that are only used by `Foo`. I'm not sure what kind of refactor this would require.

**Comment by dannosaur** [comment]
Any news on this? I'm in a position where I desperately need this feature to finish a CI implementation. I'd do it myself and submit a PR but I don't know Typescript all that well. I'd probably get there eventually but I imagine it's fairly straight forward for someone who knows the language and the project. Or if anyone has any implementation ideas or tips, I'll happily give it a go!

**Comment by tavisrudd** [comment]
I'm going to give this a shot over the next week while I bump the dependencies again.
