### ISSUE TITLE
Document $import query parameter overrides

### ISSUE THREAD

**Issue by rymndhng** [unbounce/iidy#173]
The feature implemented in #78 is *amazing* and needs to be documented.

**Comment by tavisrudd** [comment]
@tuff @jpb good thing to add to the docs

**Comment by jpb** [comment]
@rymndhng `?region=...` is included in the [README](https://github.com/unbounce/iidy#importing-data) – do you think that needs to be embellished?

**Comment by rymndhng** [comment]
Yeah, that's pretty good now. 👍
