### ISSUE TITLE
`filehash` implementation relies on bsd-specific flags

### ISSUE THREAD

**Issue by rymndhng** [unbounce/iidy#178]
Ideally, the implementation of `filehash` would work independently of the platform's tools.

On BSD shasum, the `-p` flag reads the input in portable mode. On gnu `shasum`, this flag is `-U`. 

Offending line: https://github.com/unbounce/iidy/blob/e49780fa09680d19723131673f1af3082cc88fcf/src/filehash.ts#L14

**Comment by tavisrudd** [comment]
Looks like our Makefile is doing the same. Working on a fix

**Comment by tavisrudd** [comment]
Turns out that `-p` flag has been deprecated and Macos is just out of date rather than this being something bsd specific. I'm considering using `openssl dgst -sha256` or building the hashing into iidy itself to ensure we don't run into external implicit dependency issues.

**Comment by tavisrudd** [comment]
See https://github.com/unbounce/iidy/pull/227
