### ISSUE TITLE
iidy v1.9.0 incorrectly considers Queue Policy IDs invalid

### ISSUE THREAD

**Issue by Kazzer** [unbounce/iidy#185]
Errors:
```
error Root.Resources.IncomingCommandsQueuePolicy.Properties.PolicyDocument: invalid properties: Id [IAMPolicyDocumentValidator]  
```

Code:
https://github.com/unbounce/lp-page-server-2/blob/master/infrastructure/resources/cfn-template.yaml#L110-L155

Expected:
No errors for valid syntax

This issue prevents any usage of the template.

**Comment by tavisrudd** [comment]
https://github.com/unbounce/laundry/pull/34

**Comment by tavisrudd** [comment]
Fixed upstream and the next iidy release will include that fix.
