### ISSUE TITLE
iidy v1.9.0 incorrectly considers nested functions as not allowed

### ISSUE THREAD

**Issue by Kazzer** [unbounce/iidy#186]
Errors:
```
error Root.Resources.IncomingCommandsSubscription.Properties.Region.If.2.Select.1.Split: can not be used within If [CfnFnsSupportedFnsValidator]  
```

Code:
https://github.com/unbounce/lp-page-server-2/blob/master/infrastructure/resources/cfn-template.yaml#L110-L155

Expected:
No errors for valid syntax

iidy incorrectly assumes that since `Fn::Split` is nested below an `Fn::If`, it must be invalid regardless of nest depth. `Fn::Split` is not valid directly within a `Fn::If`, but `Fn::Split` is allowed when nested in `Fn::Select` which is itself allowed when nested in `Fn::If`.

This issue prevents any usage of the template.

**Comment by Kazzer** [comment]
Also affects v1.7.0 and v1.8.0

**Comment by tavisrudd** [comment]
Fixed upstream. The next iidy release will include the fix.
