### ISSUE TITLE
Estimating costs fails when a WAF is in the stack

### ISSUE THREAD

**Issue by Kazzer** [unbounce/iidy#219]
With a WAF configured in the stack:

```
error Resource Type AWS::WAFRegional::WebACL (Logical ID: WAF) does not belong to resourceCostCalculator map.  
```

**Comment by tavisrudd** [comment]
This fails on the upstream aws cli / sdk so I'm closing it here. When they add support, we'll get it via a version bump.

**Comment by PatMyron** [comment]
[`estimate-template-cost` coverage tracking here](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/217)
