### ISSUE TITLE
Potential issue with stdout buffering

### ISSUE THREAD

**Issue by dannosaur** [unbounce/iidy#238]
This may not be an issue with iidy, but I'm raising this anyway for visibility. I use CommandsBefore to enforce templates to be linted with cfn-lint before a stack is updated.

On large templates, this fails with a "null value" error coming from cfn-lint, suspiciously on a 64k boundary. I've raised an issue on the cfn-lint project [here](https://github.com/aws-cloudformation/cfn-python-lint/issues/1268), but I'm not sure which project is to blame.

If you download the large template file that kddejong linked to, then run it through iidy (`iidy render limit_size.yaml | cfn-lint`), you'll see the problem.

Like I said, this might not be an issue with iidy, but there's definitely something weird going on here. Also, only seen with bash (which, when using CommandsBefore, ensures the issue is always seen).

**Comment by tavisrudd** [comment]
This is on `iidy`'s side. I think it might be something to do with writes to pipes being async on posix.

**Comment by tavisrudd** [comment]
Ignore that first commit referenced above. I was pushing it to a WIP branch to then cherry pick.
