### ISSUE TITLE
Linter does not properly validate `AWS::WAFv2` resources

### ISSUE THREAD

**Issue by rymndhng** [unbounce/iidy#246]
Also filed here: https://github.com/unbounce/laundry/issues/39

**Comment by tavisrudd** [comment]
Have we updated our Laundry dep here since that fix was applied upstream?

**Comment by rymndhng** [comment]
It does not appear so. 

We also need to publish a new release of laundry, the current latest version `v1.5.0` was published 7 months ago.

**Comment by tavisrudd** [comment]
I think this is fixed now.
