### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by dannosaur** [unbounce/iidy#271]
Hey,

It's been a while since the last release, and master's moved on a fair amount since 1.11.0. Any chance of a release so I don't have to keep telling my guys to pull master and compile from source? Would also help us out being able to make sure everyone's using the same version.

Dan

**Comment by tavisrudd** [comment]
Hi Dan, 
Sorry I missed the notification on this. I'm working on a dependency update and also a release at the moment. It should be ready this week.
Tavis

**Comment by tavisrudd** [comment]
At long last https://github.com/unbounce/iidy/releases/tag/v1.12.0
