### ISSUE TITLE
Document required IAM permissions

### ISSUE THREAD

**Issue by jpb** [unbounce/iidy#31]
Document the base IAM permissions to do `iidy {create, update, delete}-stack` etc. Optional: fail gracefully if permission are missing for "nice to have" output, such as describing the stack that was created.

Document additional permission required for imports, for example:
- `cfn:output:...` requires `cloudformation:DescribeStack`
- `cfn:{export, parameter, tag, resource, stack}:...` requires `cloudformation:ListExports`

**Comment by tavisrudd** [comment]
Done in new version of the README (CO-87).
