### ISSUE TITLE
Missing $import variables silently fails

### ISSUE THREAD

**Issue by jpb** [unbounce/iidy#35]
Given a template like the following:

```
$import:
  something: my-thing-{{ other }}
```

where `other` is never defined, no error is shown and errors can show up far from actual error site. Specifically in my case, a variable used in an `ssm-path` import was never set and the error was:

```
error: Error in string template at Root.Parameters.Something:
       "something" not defined in [object Object]
       Something: {{ params.something }}
```

**Comment by tavisrudd** [comment]
That's actually because of a typo of `$import` vs `$imports`. We could add a check for that and warn.

**Comment by jpb** [comment]
Sorry, my mistake when I created the issue - I was in fact using `$imports:` when I ran into this problem.

**Comment by tavisrudd** [comment]
Can you try it again? I've tested it with a bunch of different imports and I get an immediate failure on `{{other}}`

**Comment by jpb** [comment]
It looks like there is an implicit `$import` called `environment` that cased the issue I ran into. A template closer to the one I had issues with is:

```
$import:
  something: my-thing-{{ environment }}
```

I never set `environment`. It looks like this variable is always injected and defaults to `"development"`.

**Comment by tavisrudd** [comment]
Can you privately email me the ssm-path you were trying to import? I think
this is probably related to the handling of that. Other import types should
fail hard.

**Comment by jpb** [comment]
A simplified example that shows this is not related to ssm-path:

```
$ cat stack.yaml
Parameters:
  Environment:
    Type: String
$ cat stack-args.yaml
Template: stack.yaml
Parameters:
  Environment: !$ environment
$ iidy render stack-args.yaml
Template: stack.yaml
Parameters:
  Environment: development
Tags:
  environment: development
```

I think this is coming from https://github.com/unbounce/iidy/blob/7f573eaf607ac59b15190aeab5f7f557cdd4947b/src/cli.ts#L115 and https://github.com/unbounce/iidy/blob/7f573eaf607ac59b15190aeab5f7f557cdd4947b/src/cfn/index.ts#L802

This behaviour came as a surprise to me. I don't think there should be any implicit or automatic variables injected into the args file or any other template. I feel similarly about the default `Tags`: if `--environment` is never set, and the default `environment` tag is never overwritten, stacks will be mislabeled.

**Comment by tavisrudd** [comment]
How about making that behaviour happen only when an environment is explicitly set via `--environment`?
