### ISSUE TITLE
Expose region as variable

### ISSUE THREAD

**Issue by jpb** [unbounce/iidy#54]
Expose what iidy has determined to be the current region (via `--region` or environment variables) as a variable to be used in stack args file (similar to how `environment` is exposed).

**Comment by tavisrudd** [comment]
I think we should prefix this as `$region` and change `s/environment/$environment/`.

**Comment by tavisrudd** [comment]
Btw, this is already injected into `stack-args.yaml`.

**Comment by tavisrudd** [comment]
Implemented in #65
