### ISSUE TITLE
Leveraging parameter store history

### ISSUE THREAD

**Issue by jpb** [unbounce/iidy#60]
Leverage parameter store history to debug and resolve issues due to changes in parameter store values.

Running existing commands, with parameters as they were at a given point in time:

```
iidy create-stack --point-in-time '2018-01-01 3:30' stack-args.yaml
iidy update-stack --point-in-time '2018-01-01 3:30' stack-args.yaml
iidy param get-by-path --point-in-time '2018-01-01 3:30' /some/path
```

Viewing how values have changed:

```
# Show changes since date
iidy param diff /some/path 2018-01-01 
# Show changes between dates
iidy param diff /some/path '2018-01-01 3:30' '2018-01-01 4:30' 
```

**Comment by tavisrudd** [comment]
It sounds like there are two layers to this. 1) expose this sort of functionality via `iidy param` and 2) maybe integrate point-in-time (but with a better cli arg name) to the stack commands. We should probably start with 1 first.

**Comment by tavisrudd** [comment]
@jpb now that we've got the param approval stuff should we close this?
