### ISSUE TITLE
!GetAtt with array produces error

### ISSUE THREAD

**Issue by jpb** [unbounce/iidy#80]
[`!GetAtt` can be provided a dotted string or an array to lookup resource attributes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html). The latter produces an error:

```
$ cat get-att.yaml
s: !GetAtt [a, b]
$ iidy render get-att.yaml
error: ref.trim is not a function
```

**Comment by tavisrudd** [comment]
I believe this was fixed in PR #77
