### ISSUE TITLE
Region Map no longer works in iidy 1.6.4

### ISSUE THREAD

**Issue by rymndhng** [unbounce/iidy#99]
In iidy 1.6.0-rc5, you were able to specify Region as an environment map:

```
Region:
  integration: us-west-2
  production: us-east-1
```

This no longer works in iidy 1.64, instead you see this error:

```
error: Missing region in config
```

**Comment by jpb** [comment]
Do you mean: 

```
Region:
  integration: us-west-2
  production: us-east-1
```

(no array)

**Comment by rymndhng** [comment]
You're right! updating description now

**Comment by tavisrudd** [comment]
@rymndhng can you privately slack me your `stack-args.yaml`? This is still working for me in 1.6.4.

**Comment by tavisrudd** [comment]
@diorman do you still have the `stack-args.yaml` that caused this?

**Comment by diorman** [comment]
@tavisrudd

`stack-args.yaml`: https://github.com/unbounce/lp-leads/blob/586dc8776c1ea6644b3fe34a4dd06345eced91c5/infrastructure/app/stack-args.yaml

pipeline output: https://jenkins.unbounce.net/job/conv-lp-leads-staging-pipeline/235/console

**Comment by tavisrudd** [comment]
@diorman I found a bug while working on #103 that might account for what you saw (https://github.com/unbounce/iidy/pull/103/commits/5fc072d1e446c166521d995dfe3f71a8c46107a1).

**Comment by tavisrudd** [comment]
I'm going to close this now that #103 is merged. 🤞
